name: env_antigen
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipython
  - pyyaml
  - astropy
  - matplotlib
  - numpy
  - pandas
  - psutil
  - scipy
  - scikit-learn
  - scikit-image
  - seaborn
  - photutils
  - getcalspec
  - astroplan
  - astroscrappy
  - pip
  - setuptools
  - wheel
