instrument_element: "VP1R"
gain: 0.25
read_noise: 3.7
fiber_radius: 2.1
pca_components_arc: 10
reference_fiber_index: 130
sample_fiber_indices:
  - 5
  - 130
  - 230
start_wavelength: 4730
end_wavelength: 6940
detector_dimensions:
  X: 1024 # X
  Y: 2048 # Y
arc_flux_limit: 5
telescope_diameter: 2.72
overscan_length: 32
flip_x: false
flip_y: false
rotate: false
add_rows: 20